/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "generic_service_constants.h"

namespace tricycle {

const generic_serviceConstants g_generic_service_constants;

generic_serviceConstants::generic_serviceConstants() {
}

} // namespace

