/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxy_service_constants.h"

namespace tricycle {

const proxy_serviceConstants g_proxy_service_constants;

proxy_serviceConstants::proxy_serviceConstants() {
}

} // namespace

