/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef generic_service_CONSTANTS_H
#define generic_service_CONSTANTS_H

#include "generic_service_types.h"

namespace tricycle {

class generic_serviceConstants {
 public:
  generic_serviceConstants();

};

extern const generic_serviceConstants g_generic_service_constants;

} // namespace

#endif
