/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proxy_service_CONSTANTS_H
#define proxy_service_CONSTANTS_H

#include "proxy_service_types.h"

namespace tricycle {

class proxy_serviceConstants {
 public:
  proxy_serviceConstants();

};

extern const proxy_serviceConstants g_proxy_service_constants;

} // namespace

#endif
