/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProxyService_H
#define ProxyService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "proxy_service_types.h"

namespace tricycle {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProxyServiceIf {
 public:
  virtual ~ProxyServiceIf() {}
  virtual void Invoke(std::string& _return, const Request& request) = 0;
};

class ProxyServiceIfFactory {
 public:
  typedef ProxyServiceIf Handler;

  virtual ~ProxyServiceIfFactory() {}

  virtual ProxyServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyServiceIf* /* handler */) = 0;
};

class ProxyServiceIfSingletonFactory : virtual public ProxyServiceIfFactory {
 public:
  ProxyServiceIfSingletonFactory(const boost::shared_ptr<ProxyServiceIf>& iface) : iface_(iface) {}
  virtual ~ProxyServiceIfSingletonFactory() {}

  virtual ProxyServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyServiceIf> iface_;
};

class ProxyServiceNull : virtual public ProxyServiceIf {
 public:
  virtual ~ProxyServiceNull() {}
  void Invoke(std::string& /* _return */, const Request& /* request */) {
    return;
  }
};

typedef struct _ProxyService_Invoke_args__isset {
  _ProxyService_Invoke_args__isset() : request(false) {}
  bool request :1;
} _ProxyService_Invoke_args__isset;

class ProxyService_Invoke_args {
 public:

  ProxyService_Invoke_args(const ProxyService_Invoke_args&);
  ProxyService_Invoke_args& operator=(const ProxyService_Invoke_args&);
  ProxyService_Invoke_args() {
  }

  virtual ~ProxyService_Invoke_args() throw();
  Request request;

  _ProxyService_Invoke_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const ProxyService_Invoke_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const ProxyService_Invoke_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyService_Invoke_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProxyService_Invoke_pargs {
 public:


  virtual ~ProxyService_Invoke_pargs() throw();
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProxyService_Invoke_result__isset {
  _ProxyService_Invoke_result__isset() : success(false) {}
  bool success :1;
} _ProxyService_Invoke_result__isset;

class ProxyService_Invoke_result {
 public:

  ProxyService_Invoke_result(const ProxyService_Invoke_result&);
  ProxyService_Invoke_result& operator=(const ProxyService_Invoke_result&);
  ProxyService_Invoke_result() : success() {
  }

  virtual ~ProxyService_Invoke_result() throw();
  std::string success;

  _ProxyService_Invoke_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const ProxyService_Invoke_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProxyService_Invoke_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyService_Invoke_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProxyService_Invoke_presult__isset {
  _ProxyService_Invoke_presult__isset() : success(false) {}
  bool success :1;
} _ProxyService_Invoke_presult__isset;

class ProxyService_Invoke_presult {
 public:


  virtual ~ProxyService_Invoke_presult() throw();
  std::string* success;

  _ProxyService_Invoke_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProxyServiceClient : virtual public ProxyServiceIf {
 public:
  ProxyServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Invoke(std::string& _return, const Request& request);
  void send_Invoke(const Request& request);
  void recv_Invoke(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Invoke(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyServiceProcessor(boost::shared_ptr<ProxyServiceIf> iface) :
    iface_(iface) {
    processMap_["Invoke"] = &ProxyServiceProcessor::process_Invoke;
  }

  virtual ~ProxyServiceProcessor() {}
};

class ProxyServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyServiceProcessorFactory(const ::boost::shared_ptr< ProxyServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyServiceIfFactory > handlerFactory_;
};

class ProxyServiceMultiface : virtual public ProxyServiceIf {
 public:
  ProxyServiceMultiface(std::vector<boost::shared_ptr<ProxyServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyServiceIf> > ifaces_;
  ProxyServiceMultiface() {}
  void add(boost::shared_ptr<ProxyServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Invoke(std::string& _return, const Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Invoke(_return, request);
    }
    ifaces_[i]->Invoke(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProxyServiceConcurrentClient : virtual public ProxyServiceIf {
 public:
  ProxyServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Invoke(std::string& _return, const Request& request);
  int32_t send_Invoke(const Request& request);
  void recv_Invoke(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
