// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#ifndef TRICYCLE_TRICYCLE_SERVER_HPP
#define TRICYCLE_TRICYCLE_SERVER_HPP

#include "proxy_service.h"

namespace tricycle {

    class ProxyServiceHandler : virtual public ProxyServiceIf {
    public:
        void Invoke(std::string &_return, const Request &request);

    };

    class TricycleServer {
    public:
        void Serve(int port);
    };

}

#endif

